In [74]:
import json
import pandas as pd

In [75]:
df = pd.read_csv("../data/data-gov-india/industry-state-and-year-wise-startups-recognized-dpiit.csv")

In [76]:
df.describe()

             S No.         Year        Count
count  9933.000000  9933.000000  9933.000000
mean   4967.000000  2021.427665    20.853217
std    2867.554446     2.533848    46.171438
min       1.000000  2016.000000     1.000000
25%    2484.000000  2019.000000     2.000000
50%    4967.000000  2022.000000     6.000000
75%    7450.000000  2024.000000    19.000000
max    9933.000000  2025.000000   791.000000

In [77]:
yearly_df = df.groupby('Year')[['Count']].sum().reset_index()
display(yearly_df.head())

   Year  Count
0  2016    502
1  2017   5473
2  2018   8980
3  2019  11885
4  2020  14852

In [78]:
state_df = df.groupby(by=['Year', 'State'])[['Count']].sum().reset_index()
display(state_df.head())

   Year           State  Count
0  2016  Andhra Pradesh      4
1  2016           Assam     10
2  2016           Bihar      1
3  2016      Chandigarh      9
4  2016    Chhattisgarh     11

In [79]:
yearly_df.to_dict(orient='records')

[{'Year': 2016, 'Count': 502},
 {'Year': 2017, 'Count': 5473},
 {'Year': 2018, 'Count': 8980},
 {'Year': 2019, 'Count': 11885},
 {'Year': 2020, 'Count': 14852},
 {'Year': 2021, 'Count': 20282},
 {'Year': 2022, 'Count': 26595},
 {'Year': 2023, 'Count': 34842},
 {'Year': 2024, 'Count': 34294},
 {'Year': 2025, 'Count': 49430}]

In [80]:
state_df.to_dict(orient='records')

[{'Year': 2016, 'State': 'Andhra Pradesh', 'Count': 4},
 {'Year': 2016, 'State': 'Assam', 'Count': 10},
 {'Year': 2016, 'State': 'Bihar', 'Count': 1},
 {'Year': 2016, 'State': 'Chandigarh', 'Count': 9},
 {'Year': 2016, 'State': 'Chhattisgarh', 'Count': 11},
 {'Year': 2016, 'State': 'Delhi', 'Count': 74},
 {'Year': 2016, 'State': 'Goa', 'Count': 2},
 {'Year': 2016, 'State': 'Gujarat', 'Count': 29},
 {'Year': 2016, 'State': 'Haryana', 'Count': 28},
 {'Year': 2016, 'State': 'Jammu and Kashmir', 'Count': 2},
 {'Year': 2016, 'State': 'Jharkhand', 'Count': 2},
 {'Year': 2016, 'State': 'Karnataka', 'Count': 67},
 {'Year': 2016, 'State': 'Kerala', 'Count': 25},
 {'Year': 2016, 'State': 'Madhya Pradesh', 'Count': 7},
 {'Year': 2016, 'State': 'Maharashtra', 'Count': 93},
 {'Year': 2016, 'State': 'Nagaland', 'Count': 1},
 {'Year': 2016, 'State': 'Odisha', 'Count': 4},
 {'Year': 2016, 'State': 'Punjab', 'Count': 7},
 {'Year': 2016, 'State': 'Rajasthan', 'Count': 14},
 {'Year': 2016, 'State': 'Tamil Nadu', 'Count': 52},
 {'Year': 2016, 'State': 'Telangana', 'Count': 20},
 {'Year': 2016, 'State': 'Uttar Pradesh', 'Count': 28},
 {'Year': 2016, 'State': 'Uttarakhand', 'Count': 4},
 {'Year': 2016, 'State': 'West Bengal', 'Count': 8},
 {'Year': 2017, 'State': 'Andaman and Nicobar Islands', 'Count': 1},
 {'Year': 2017, 'State': 'Andhra Pradesh', 'Count': 103},
 {'Year': 2017, 'State': 'Assam', 'Count': 35},
 {'Year': 2017, 'State': 'Bihar', 'Count': 47},
 {'Year': 2017, 'State': 'Chandigarh', 'Count': 22},
 {'Year': 2017, 'State': 'Chhattisgarh', 'Count': 57},
 {'Year': 2017,
  'State': 'Dadra and Nagar Haveli and Daman and Diu',
  'Count': 4},
 {'Year': 2017, 'State': 'Delhi', 'Count': 742},
 {'Year': 2017, 'State': 'Goa', 'Count': 20},
 {'Year': 2017, 'State': 'Gujarat', 'Count': 299},
 {'Year': 2017, 'State': 'Haryana', 'Count': 270},
 {'Year': 2017, 'State': 'Himachal Pradesh', 'Count': 9},
 {'Year': 2017, 'State': 'Jammu and Kashmir', 'Count': 15},
 {'Year': 2017, 'State': 'Jharkhand', 'Count': 35},
 {'Year': 2017, 'State': 'Karnataka', 'Count': 889},
 {'Year': 2017, 'State': 'Kerala', 'Count': 172},
 {'Year': 2017, 'State': 'Madhya Pradesh', 'Count': 108},
 {'Year': 2017, 'State': 'Maharashtra', 'Count': 1107},
 {'Year': 2017, 'State': 'Manipur', 'Count': 4},
 {'Year': 2017, 'State': 'Nagaland', 'Count': 4},
 {'Year': 2017, 'State': 'Odisha', 'Count': 115},
 {'Year': 2017, 'State': 'Puducherry', 'Count': 3},
 {'Year': 2017, 'State': 'Punjab', 'Count': 31},
 {'Year': 2017, 'State': 'Rajasthan', 'Count': 140},
 {'Year': 2017, 'State': 'Sikkim', 'Count': 1},
 {'Year': 2017, 'State': 'Tamil Nadu', 'Count': 272},
 {'Year': 2017, 'State': 'Telangana', 'Count': 328},
 {'Year': 2017, 'State': 'Uttar Pradesh', 'Count': 414},
 {'Year': 2017, 'State': 'Uttarakhand', 'Count': 45},
 {'Year': 2017, 'State': 'West Bengal', 'Count': 181},
 {'Year': 2018, 'State': 'Andaman and Nicobar Islands', 'Count': 2},
 {'Year': 2018, 'State': 'Andhra Pradesh', 'Count': 161},
 {'Year': 2018, 'State': 'Arunachal Pradesh', 'Count': 2},
 {'Year': 2018, 'State': 'Assam', 'Count': 68},
 {'Year': 2018, 'State': 'Bihar', 'Count': 148},
 {'Year': 2018, 'State': 'Chandigarh', 'Count': 27},
 {'Year': 2018, 'State': 'Chhattisgarh', 'Count': 121},
 {'Year': 2018,
  'State': 'Dadra and Nagar Haveli and Daman and Diu',
  'Count': 1},
 {'Year': 2018, 'State': 'Delhi', 'Count': 1189},
 {'Year': 2018, 'State': 'Goa', 'Count': 44},
 {'Year': 2018, 'State': 'Gujarat', 'Count': 449},
 {'Year': 2018, 'State': 'Haryana', 'Count': 488},
 {'Year': 2018, 'State': 'Himachal Pradesh', 'Count': 17},
 {'Year': 2018, 'State': 'Jammu and Kashmir', 'Count': 47},
 {'Year': 2018, 'State': 'Jharkhand', 'Count': 88},
 {'Year': 2018, 'State': 'Karnataka', 'Count': 1212},
 {'Year': 2018, 'State': 'Kerala', 'Count': 333},
 {'Year': 2018, 'State': 'Ladakh', 'Count': 1},
 {'Year': 2018, 'State': 'Madhya Pradesh', 'Count': 297},
 {'Year': 2018, 'State': 'Maharashtra', 'Count': 1662},
 {'Year': 2018, 'State': 'Manipur', 'Count': 7},
 {'Year': 2018, 'State': 'Meghalaya', 'Count': 2},
 {'Year': 2018, 'State': 'Mizoram', 'Count': 2},
 {'Year': 2018, 'State': 'Nagaland', 'Count': 2},
 {'Year': 2018, 'State': 'Odisha', 'Count': 168},
 {'Year': 2018, 'State': 'Puducherry', 'Count': 16},
 {'Year': 2018, 'State': 'Punjab', 'Count': 70},
 {'Year': 2018, 'State': 'Rajasthan', 'Count': 246},
 {'Year': 2018, 'State': 'Tamil Nadu', 'Count': 459},
 {'Year': 2018, 'State': 'Telangana', 'Count': 512},
 {'Year': 2018, 'State': 'Tripura', 'Count': 4},
 {'Year': 2018, 'State': 'Uttar Pradesh', 'Count': 790},
 {'Year': 2018, 'State': 'Uttarakhand', 'Count': 69},
 {'Year': 2018, 'State': 'West Bengal', 'Count': 276},
 {'Year': 2019, 'State': 'Andaman and Nicobar Islands', 'Count': 8},
 {'Year': 2019, 'State': 'Andhra Pradesh', 'Count': 179},
 {'Year': 2019, 'State': 'Arunachal Pradesh', 'Count': 2},
 {'Year': 2019, 'State': 'Assam', 'Count': 71},
 {'Year': 2019, 'State': 'Bihar', 'Count': 158},
 {'Year': 2019, 'State': 'Chandigarh', 'Count': 41},
 {'Year': 2019, 'State': 'Chhattisgarh', 'Count': 166},
 {'Year': 2019,
  'State': 'Dadra and Nagar Haveli and Daman and Diu',
  'Count': 3},
 {'Year': 2019, 'State': 'Delhi', 'Count': 1450},
 {'Year': 2019, 'State': 'Goa', 'Count': 43},
 {'Year': 2019, 'State': 'Gujarat', 'Count': 644},
 {'Year': 2019, 'State': 'Haryana', 'Count': 730},
 {'Year': 2019, 'State': 'Himachal Pradesh', 'Count': 31},
 {'Year': 2019, 'State': 'Jammu and Kashmir', 'Count': 38},
 {'Year': 2019, 'State': 'Jharkhand', 'Count': 89},
 {'Year': 2019, 'State': 'Karnataka', 'Count': 1746},
 {'Year': 2019, 'State': 'Kerala', 'Count': 669},
 {'Year': 2019, 'State': 'Madhya Pradesh', 'Count': 335},
 {'Year': 2019, 'State': 'Maharashtra', 'Count': 2228},
 {'Year': 2019, 'State': 'Manipur', 'Count': 6},
 {'Year': 2019, 'State': 'Meghalaya', 'Count': 6},
 {'Year': 2019, 'State': 'Mizoram', 'Count': 1},
 {'Year': 2019, 'State': 'Nagaland', 'Count': 2},
 {'Year': 2019, 'State': 'Odisha', 'Count': 187},
 {'Year': 2019, 'State': 'Puducherry', 'Count': 11},
 {'Year': 2019, 'State': 'Punjab', 'Count': 99},
 {'Year': 2019, 'State': 'Rajasthan', 'Count': 358},
 {'Year': 2019, 'State': 'Sikkim', 'Count': 2},
 {'Year': 2019, 'State': 'Tamil Nadu', 'Count': 632},
 {'Year': 2019, 'State': 'Telangana', 'Count': 620},
 {'Year': 2019, 'State': 'Tripura', 'Count': 7},
 {'Year': 2019, 'State': 'Uttar Pradesh', 'Count': 905},
 {'Year': 2019, 'State': 'Uttarakhand', 'Count': 98},
 {'Year': 2019, 'State': 'West Bengal', 'Count': 320},
 {'Year': 2020, 'State': 'Andaman and Nicobar Islands', 'Count': 5},
 {'Year': 2020, 'State': 'Andhra Pradesh', 'Count': 235},
 {'Year': 2020, 'State': 'Assam', 'Count': 119},
 {'Year': 2020, 'State': 'Bihar', 'Count': 265},
 {'Year': 2020, 'State': 'Chandigarh', 'Count': 55},
 {'Year': 2020, 'State': 'Chhattisgarh', 'Count': 155},
 {'Year': 2020,
  'State': 'Dadra and Nagar Haveli and Daman and Diu',
  'Count': 5},
 {'Year': 2020, 'State': 'Delhi', 'Count': 1815},
 {'Year': 2020, 'State': 'Goa', 'Count': 67},
 {'Year': 2020, 'State': 'Gujarat', 'Count': 882},
 {'Year': 2020, 'State': 'Haryana', 'Count': 831},
 {'Year': 2020, 'State': 'Himachal Pradesh', 'Count': 41},
 {'Year': 2020, 'State': 'Jammu and Kashmir', 'Count': 64},
 {'Year': 2020, 'State': 'Jharkhand', 'Count': 165},
 {'Year': 2020, 'State': 'Karnataka', 'Count': 1776},
 {'Year': 2020, 'State': 'Kerala', 'Count': 710},
 {'Year': 2020, 'State': 'Ladakh', 'Count': 1},
 {'Year': 2020, 'State': 'Lakshadweep', 'Count': 1},
 {'Year': 2020, 'State': 'Madhya Pradesh', 'Count': 427},
 {'Year': 2020, 'State': 'Maharashtra', 'Count': 2737},
 {'Year': 2020, 'State': 'Manipur', 'Count': 13},
 {'Year': 2020, 'State': 'Mizoram', 'Count': 1},
 {'Year': 2020, 'State': 'Nagaland', 'Count': 5},
 {'Year': 2020, 'State': 'Odisha', 'Count': 280},
 {'Year': 2020, 'State': 'Puducherry', 'Count': 14},
 {'Year': 2020, 'State': 'Punjab', 'Count': 146},
 {'Year': 2020, 'State': 'Rajasthan', 'Count': 502},
 {'Year': 2020, 'State': 'Sikkim', 'Count': 1},
 {'Year': 2020, 'State': 'Tamil Nadu', 'Count': 772},
 {'Year': 2020, 'State': 'Telangana', 'Count': 819},
 {'Year': 2020, 'State': 'Tripura', 'Count': 23},
 {'Year': 2020, 'State': 'Uttar Pradesh', 'Count': 1401},
 {'Year': 2020, 'State': 'Uttarakhand', 'Count': 114},
 {'Year': 2020, 'State': 'West Bengal', 'Count': 405},
 {'Year': 2021, 'State': 'Andaman and Nicobar Islands', 'Count': 13},
 {'Year': 2021, 'State': 'Andhra Pradesh', 'Count': 299},
 {'Year': 2021, 'State': 'Arunachal Pradesh', 'Count': 5},
 {'Year': 2021, 'State': 'Assam', 'Count': 190},
 {'Year': 2021, 'State': 'Bihar', 'Count': 390},
 {'Year': 2021, 'State': 'Chandigarh', 'Count': 69},
 {'Year': 2021, 'State': 'Chhattisgarh', 'Count': 168},
 {'Year': 2021,
  'State': 'Dadra and Nagar Haveli and Daman and Diu',
  'Count': 12},
 {'Year': 2021, 'State': 'Delhi', 'Count': 2215},
 {'Year': 2021, 'State': 'Goa', 'Count': 81},
 {'Year': 2021, 'State': 'Gujarat', 'Count': 1729},
 {'Year': 2021, 'State': 'Haryana', 'Count': 1070},
 {'Year': 2021, 'State': 'Himachal Pradesh', 'Count': 56},
 {'Year': 2021, 'State': 'Jammu and Kashmir', 'Count': 131},
 {'Year': 2021, 'State': 'Jharkhand', 'Count': 191},
 {'Year': 2021, 'State': 'Karnataka', 'Count': 2157},
 {'Year': 2021, 'State': 'Kerala', 'Count': 923},
 {'Year': 2021, 'State': 'Ladakh', 'Count': 1},
 {'Year': 2021, 'State': 'Madhya Pradesh', 'Count': 562},
 {'Year': 2021, 'State': 'Maharashtra', 'Count': 3736},
 {'Year': 2021, 'State': 'Manipur', 'Count': 37},
 {'Year': 2021, 'State': 'Meghalaya', 'Count': 9},
 {'Year': 2021, 'State': 'Mizoram', 'Count': 2},
 {'Year': 2021, 'State': 'Nagaland', 'Count': 6},
 {'Year': 2021, 'State': 'Odisha', 'Count': 397},
 {'Year': 2021, 'State': 'Puducherry', 'Count': 17},
 {'Year': 2021, 'State': 'Punjab', 'Count': 244},
 {'Year': 2021, 'State': 'Rajasthan', 'Count': 622},
 {'Year': 2021, 'State': 'Sikkim', 'Count': 4},
 {'Year': 2021, 'State': 'Tamil Nadu', 'Count': 1107},
 {'Year': 2021, 'State': 'Telangana', 'Count': 993},
 {'Year': 2021, 'State': 'Tripura', 'Count': 12},
 {'Year': 2021, 'State': 'Uttar Pradesh', 'Count': 1981},
 {'Year': 2021, 'State': 'Uttarakhand', 'Count': 162},
 {'Year': 2021, 'State': 'West Bengal', 'Count': 691},
 {'Year': 2022, 'State': 'Andaman and Nicobar Islands', 'Count': 9},
 {'Year': 2022, 'State': 'Andhra Pradesh', 'Count': 381},
 {'Year': 2022, 'State': 'Arunachal Pradesh', 'Count': 9},
 {'Year': 2022, 'State': 'Assam', 'Count': 285},
 {'Year': 2022, 'State': 'Bihar', 'Count': 526},
 {'Year': 2022, 'State': 'Chandigarh', 'Count': 81},
 {'Year': 2022, 'State': 'Chhattisgarh', 'Count': 237},
 {'Year': 2022,
  'State': 'Dadra and Nagar Haveli and Daman and Diu',
  'Count': 12},
 {'Year': 2022, 'State': 'Delhi', 'Count': 2580},
 {'Year': 2022, 'State': 'Goa', 'Count': 107},
 {'Year': 2022, 'State': 'Gujarat', 'Count': 2283},
 {'Year': 2022, 'State': 'Haryana', 'Count': 1335},
 {'Year': 2022, 'State': 'Himachal Pradesh', 'Count': 120},
 {'Year': 2022, 'State': 'Jammu and Kashmir', 'Count': 169},
 {'Year': 2022, 'State': 'Jharkhand', 'Count': 239},
 {'Year': 2022, 'State': 'Karnataka', 'Count': 2568},
 {'Year': 2022, 'State': 'Kerala', 'Count': 1078},
 {'Year': 2022, 'State': 'Ladakh', 'Count': 5},
 {'Year': 2022, 'State': 'Madhya Pradesh', 'Count': 898},
 {'Year': 2022, 'State': 'Maharashtra', 'Count': 4811},
 {'Year': 2022, 'State': 'Manipur', 'Count': 31},
 {'Year': 2022, 'State': 'Meghalaya', 'Count': 10},
 {'Year': 2022, 'State': 'Mizoram', 'Count': 6},
 {'Year': 2022, 'State': 'Nagaland', 'Count': 7},
 {'Year': 2022, 'State': 'Odisha', 'Count': 451},
 {'Year': 2022, 'State': 'Puducherry', 'Count': 29},
 {'Year': 2022, 'State': 'Punjab', 'Count': 294},
 {'Year': 2022, 'State': 'Rajasthan', 'Count': 992},
 {'Year': 2022, 'State': 'Sikkim', 'Count': 2},
 {'Year': 2022, 'State': 'Tamil Nadu', 'Count': 1812},
 {'Year': 2022, 'State': 'Telangana', 'Count': 1381},
 {'Year': 2022, 'State': 'Tripura', 'Count': 27},
 {'Year': 2022, 'State': 'Uttar Pradesh', 'Count': 2582},
 {'Year': 2022, 'State': 'Uttarakhand', 'Count': 236},
 {'Year': 2022, 'State': 'West Bengal', 'Count': 1002},
 {'Year': 2023, 'State': 'Andaman and Nicobar Islands', 'Count': 13},
 {'Year': 2023, 'State': 'Andhra Pradesh', 'Count': 586},
 {'Year': 2023, 'State': 'Arunachal Pradesh', 'Count': 17},
 {'Year': 2023, 'State': 'Assam', 'Count': 361},
 {'Year': 2023, 'State': 'Bihar', 'Count': 813},
 {'Year': 2023, 'State': 'Chandigarh', 'Count': 126},
 {'Year': 2023, 'State': 'Chhattisgarh', 'Count': 362},
 {'Year': 2023,
  'State': 'Dadra and Nagar Haveli and Daman and Diu',
  'Count': 11},
 {'Year': 2023, 'State': 'Delhi', 'Count': 3159},
 {'Year': 2023, 'State': 'Goa', 'Count': 98},
 {'Year': 2023, 'State': 'Gujarat', 'Count': 3295},
 {'Year': 2023, 'State': 'Haryana', 'Count': 1743},
 {'Year': 2023, 'State': 'Himachal Pradesh', 'Count': 144},
 {'Year': 2023, 'State': 'Jammu and Kashmir', 'Count': 246},
 {'Year': 2023, 'State': 'Jharkhand', 'Count': 337},
 {'Year': 2023, 'State': 'Karnataka', 'Count': 3034},
 {'Year': 2023, 'State': 'Kerala', 'Count': 1296},
 {'Year': 2023, 'State': 'Ladakh', 'Count': 5},
 {'Year': 2023, 'State': 'Lakshadweep', 'Count': 2},
 {'Year': 2023, 'State': 'Madhya Pradesh', 'Count': 1267},
 {'Year': 2023, 'State': 'Maharashtra', 'Count': 5816},
 {'Year': 2023, 'State': 'Manipur', 'Count': 26},
 {'Year': 2023, 'State': 'Meghalaya', 'Count': 18},
 {'Year': 2023, 'State': 'Mizoram', 'Count': 13},
 {'Year': 2023, 'State': 'Nagaland', 'Count': 22},
 {'Year': 2023, 'State': 'Odisha', 'Count': 620},
 {'Year': 2023, 'State': 'Puducherry', 'Count': 43},
 {'Year': 2023, 'State': 'Punjab', 'Count': 443},
 {'Year': 2023, 'State': 'Rajasthan', 'Count': 1445},
 {'Year': 2023, 'State': 'Sikkim', 'Count': 2},
 {'Year': 2023, 'State': 'Tamil Nadu', 'Count': 2816},
 {'Year': 2023, 'State': 'Telangana', 'Count': 1760},
 {'Year': 2023, 'State': 'Tripura', 'Count': 23},
 {'Year': 2023, 'State': 'Uttar Pradesh', 'Count': 3435},
 {'Year': 2023, 'State': 'Uttarakhand', 'Count': 271},
 {'Year': 2023, 'State': 'West Bengal', 'Count': 1174},
 {'Year': 2024, 'State': 'Andaman and Nicobar Islands', 'Count': 20},
 {'Year': 2024, 'State': 'Andhra Pradesh', 'Count': 606},
 {'Year': 2024, 'State': 'Arunachal Pradesh', 'Count': 13},
 {'Year': 2024, 'State': 'Assam', 'Count': 347},
 {'Year': 2024, 'State': 'Bihar', 'Count': 841},
 {'Year': 2024, 'State': 'Chandigarh', 'Count': 102},
 {'Year': 2024, 'State': 'Chhattisgarh', 'Count': 460},
 {'Year': 2024,
  'State': 'Dadra and Nagar Haveli and Daman and Diu',
  'Count': 16},
 {'Year': 2024, 'State': 'Delhi', 'Count': 2853},
 {'Year': 2024, 'State': 'Goa', 'Count': 125},
 {'Year': 2024, 'State': 'Gujarat', 'Count': 3445},
 {'Year': 2024, 'State': 'Haryana', 'Count': 1730},
 {'Year': 2024, 'State': 'Himachal Pradesh', 'Count': 145},
 {'Year': 2024, 'State': 'Jammu and Kashmir', 'Count': 273},
 {'Year': 2024, 'State': 'Jharkhand', 'Count': 331},
 {'Year': 2024, 'State': 'Karnataka', 'Count': 3174},
 {'Year': 2024, 'State': 'Kerala', 'Count': 1155},
 {'Year': 2024, 'State': 'Ladakh', 'Count': 5},
 {'Year': 2024, 'State': 'Madhya Pradesh', 'Count': 1194},
 {'Year': 2024, 'State': 'Maharashtra', 'Count': 5736},
 {'Year': 2024, 'State': 'Manipur', 'Count': 55},
 {'Year': 2024, 'State': 'Meghalaya', 'Count': 17},
 {'Year': 2024, 'State': 'Mizoram', 'Count': 16},
 {'Year': 2024, 'State': 'Nagaland', 'Count': 35},
 {'Year': 2024, 'State': 'Odisha', 'Count': 548},
 {'Year': 2024, 'State': 'Puducherry', 'Count': 27},
 {'Year': 2024, 'State': 'Punjab', 'Count': 406},
 {'Year': 2024, 'State': 'Rajasthan', 'Count': 1246},
 {'Year': 2024, 'State': 'Tamil Nadu', 'Count': 2656},
 {'Year': 2024, 'State': 'Telangana', 'Count': 1809},
 {'Year': 2024, 'State': 'Tripura', 'Count': 45},
 {'Year': 2024, 'State': 'Uttar Pradesh', 'Count': 3486},
 {'Year': 2024, 'State': 'Uttarakhand', 'Count': 270},
 {'Year': 2024, 'State': 'West Bengal', 'Count': 1107},
 {'Year': 2025, 'State': 'Andaman and Nicobar Islands', 'Count': 18},
 {'Year': 2025, 'State': 'Andhra Pradesh', 'Count': 1333},
 {'Year': 2025, 'State': 'Arunachal Pradesh', 'Count': 37},
 {'Year': 2025, 'State': 'Assam', 'Count': 528},
 {'Year': 2025, 'State': 'Bihar', 'Count': 1376},
 {'Year': 2025, 'State': 'Chandigarh', 'Count': 128},
 {'Year': 2025, 'State': 'Chhattisgarh', 'Count': 508},
 {'Year': 2025,
  'State': 'Dadra and Nagar Haveli and Daman and Diu',
  'Count': 25},
 {'Year': 2025, 'State': 'Delhi', 'Count': 3837},
 {'Year': 2025, 'State': 'Goa', 'Count': 186},
 {'Year': 2025, 'State': 'Gujarat', 'Count': 4637},
 {'Year': 2025, 'State': 'Haryana', 'Count': 2519},
 {'Year': 2025, 'State': 'Himachal Pradesh', 'Count': 199},
 {'Year': 2025, 'State': 'Jammu and Kashmir', 'Count': 412},
 {'Year': 2025, 'State': 'Jharkhand', 'Count': 467},
 {'Year': 2025, 'State': 'Karnataka', 'Count': 4541},
 {'Year': 2025, 'State': 'Kerala', 'Count': 1729},
 {'Year': 2025, 'State': 'Ladakh', 'Count': 7},
 {'Year': 2025, 'State': 'Madhya Pradesh', 'Count': 1724},
 {'Year': 2025, 'State': 'Maharashtra', 'Count': 8067},
 {'Year': 2025, 'State': 'Manipur', 'Count': 72},
 {'Year': 2025, 'State': 'Meghalaya', 'Count': 27},
 {'Year': 2025, 'State': 'Mizoram', 'Count': 21},
 {'Year': 2025, 'State': 'Nagaland', 'Count': 30},
 {'Year': 2025, 'State': 'Odisha', 'Count': 819},
 {'Year': 2025, 'State': 'Puducherry', 'Count': 59},
 {'Year': 2025, 'State': 'Punjab', 'Count': 566},
 {'Year': 2025, 'State': 'Rajasthan', 'Count': 1925},
 {'Year': 2025, 'State': 'Sikkim', 'Count': 6},
 {'Year': 2025, 'State': 'Tamil Nadu', 'Count': 3201},
 {'Year': 2025, 'State': 'Telangana', 'Count': 3192},
 {'Year': 2025, 'State': 'Tripura', 'Count': 50},
 {'Year': 2025, 'State': 'Uttar Pradesh', 'Count': 5141},
 {'Year': 2025, 'State': 'Uttarakhand', 'Count': 440},
 {'Year': 2025, 'State': 'West Bengal', 'Count': 1603}]

In [81]:
with open('../data/data-gov-india/industry-state-and-year-wise-startups-recognized-dpiit.json', 'w') as f:
    json.dump(yearly_df.to_dict(orient='records'), f, indent=2)